// <auto-generated>
// CP932 (Windows-31J / Shift-JIS) -> Unicode decoder with the mapping tables embedded as source, so it works without
// System.Text.Encoding.GetEncoding(932). That throws NotSupportedException on IL2CPP/WebGL (the CJK code-page assembly
// is absent), and registering CodePagesEncodingProvider is worse there - its data tables fail to load and corrupt
// Unity's own TextAsset decoding. This self-contained decoder avoids both.
//
// Two tables, both generated from .NET's CP932 encoding (do not edit the base64 by hand; regenerate it):
//   * single-byte: 256 entries, byte -> UTF-16 code unit. 0xFFFF marks a double-byte lead; 0xFFFD marks undefined.
//   * double-byte: [leadIndex * k_TrailCount + (trail - k_TrailStart)] -> UTF-16 code unit (0 = undefined).
// </auto-generated>
using System;
using System.Text;

namespace UMT
{
    /// <summary>
    /// Decodes CP932 (Shift-JIS) bytes to a UTF-16 string without relying on <see cref="Encoding.GetEncoding(int)"/>.
    /// Every byte is resolved through an embedded table: single bytes map directly, while a lead byte (marked
    /// <see cref="k_DoubleByteLead"/> in the single-byte table) consumes a trailing byte and maps through the
    /// double-byte table. Undefined sequences decode to U+FFFD (replacement character).
    /// </summary>
    public static class ShiftJisDecoder
    {
        private const int k_TrailStart = 0x40;
        private const int k_TrailEnd = 0xFC;
        private const int k_TrailCount = k_TrailEnd - k_TrailStart + 1; // 189
        private const ushort k_DoubleByteLead = 0xFFFF; // sentinel in the single-byte table marking a lead byte
        private const char k_Replacement = '�';

        private static ushort[] s_SingleByte;
        private static ushort[] s_DoubleByte;

        // 256 entries: byte -> UTF-16 code unit (0xFFFF = double-byte lead, 0xFFFD = undefined).
        private static readonly string k_SingleByteBase64 =
            "AAABAAIAAwAEAAUABgAHAAgACQAKAAsADAANAA4ADwAQABEAEgATABQAFQAWABcAGAAZABoAGwAcAB0AHgAfACAAIQAiACMAJAAlACYAJwAoACkAKgArACwA" +
            "LQAuAC8AMAAxADIAMwA0ADUANgA3ADgAOQA6ADsAPAA9AD4APwBAAEEAQgBDAEQARQBGAEcASABJAEoASwBMAE0ATgBPAFAAUQBSAFMAVABVAFYAVwBYAFkA" +
            "WgBbAFwAXQBeAF8AYABhAGIAYwBkAGUAZgBnAGgAaQBqAGsAbABtAG4AbwBwAHEAcgBzAHQAdQB2AHcAeAB5AHoAewB8AH0AfgB/AIAA////////////////" +
            "///////////////////////////////////////////////////////////////////w+GH/Yv9j/2T/Zf9m/2f/aP9p/2r/a/9s/23/bv9v/3D/cf9y/3P/" +
            "dP91/3b/d/94/3n/ev97/3z/ff9+/3//gP+B/4L/g/+E/4X/hv+H/4j/if+K/4v/jP+N/47/j/+Q/5H/kv+T/5T/lf+W/5f/mP+Z/5r/m/+c/53/nv+f////" +
            "///////////////////////////////////////////////////////////////////////////x+PL48/g=";

        // Flattened [leadIndex * k_TrailCount + (trail - k_TrailStart)] -> UTF-16 code unit; 0 means undefined.
        private static readonly string k_DoubleByteBase64 =
            "ADABMAIwDP8O//swGv8b/x//Af+bMJwwtABA/6gAPv/j/z///TD+MJ0wnjADMN1OBTAGMAcw/DAVIBAgD/88/17/JSJc/yYgJSAYIBkgHCAdIAj/Cf8UMBUw" +
            "O/89/1v/Xf8IMAkwCjALMAwwDTAOMA8wEDARMAv/Df+xANcAAAD3AB3/YCIc/x7/ZiJnIh4iNCJCJkAmsAAyIDMgAyHl/wT/4P/h/wX/A/8G/wr/IP+nAAYm" +
            "BSbLJc8lziXHJcYloSWgJbMlsiW9JbwlOyASMJIhkCGRIZMhEzD7MPsw+zD7MPsw+zD7MPsw+zD7MPswCCILIoYihyKCIoMiKiIpIvsw+zD7MPsw+zD7MPsw" +
            "+zAnIigi4v/SIdQhACIDIvsw+zD7MPsw+zD7MPsw+zD7MPsw+zAgIqUiEiMCIgciYSJSImoiayIaIj0iHSI1IisiLCL7MPsw+zD7MPsw+zD7MCshMCBvJm0m" +
            "aiYgICEgtgD7MPsw+zD7MO8l+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPswEP8R/xL/E/8U/xX/Fv8X/xj/Gf/7MPsw+zD7MPsw+zD7MCH/Iv8j/yT/" +
            "Jf8m/yf/KP8p/yr/K/8s/y3/Lv8v/zD/Mf8y/zP/NP81/zb/N/84/zn/Ov/7MPsw+zD7MPswAAD7MEH/Qv9D/0T/Rf9G/0f/SP9J/0r/S/9M/03/Tv9P/1D/" +
            "Uf9S/1P/VP9V/1b/V/9Y/1n/Wv/7MPsw+zD7MEEwQjBDMEQwRTBGMEcwSDBJMEowSzBMME0wTjBPMFAwUTBSMFMwVDBVMFYwVzBYMFkwWjBbMFwwXTBeMF8w" +
            "YDBhMGIwYzBkMGUwZjBnMGgwaTBqMGswbDBtMG4wbzBwMHEwcjBzMHQwdTB2MHcweDB5MHowezB8MH0wfjB/MIAwgTCCMIMwhDCFMIYwhzCIMIkwijCLMIww" +
            "jTCOMI8wkDCRMJIwkzD7MPsw+zD7MPsw+zD7MPsw+zD7MPswoTCiMKMwpDClMKYwpzCoMKkwqjCrMKwwrTCuMK8wsDCxMLIwszC0MLUwtjC3MLgwuTC6MLsw" +
            "vDC9ML4wvzDAMMEwwjDDMMQwxTDGMMcwyDDJMMowyzDMMM0wzjDPMNAw0TDSMNMw1DDVMNYw1zDYMNkw2jDbMNww3TDeMN8wAADgMOEw4jDjMOQw5TDmMOcw" +
            "6DDpMOow6zDsMO0w7jDvMPAw8TDyMPMw9DD1MPYw+zD7MPsw+zD7MPsw+zD7MJEDkgOTA5QDlQOWA5cDmAOZA5oDmwOcA50DngOfA6ADoQOjA6QDpQOmA6cD" +
            "qAOpA/sw+zD7MPsw+zD7MPsw+zCxA7IDswO0A7UDtgO3A7gDuQO6A7sDvAO9A74DvwPAA8EDwwPEA8UDxgPHA8gDyQP7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPswEAQRBBIEEwQUBBUEAQQWBBcEGAQZBBoEGwQcBB0EHgQfBCAE" +
            "IQQiBCMEJAQlBCYEJwQoBCkEKgQrBCwELQQuBC8E+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPswMAQxBDIEMwQ0BDUEUQQ2BDcEOAQ5BDoEOwQ8BD0E" +
            "AAA+BD8EQARBBEIEQwREBEUERgRHBEgESQRKBEsETARNBE4ETwT7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MAAlAiUMJRAlGCUUJRwlLCUkJTQlPCUBJQMl" +
            "DyUTJRslFyUjJTMlKyU7JUslICUvJSglNyU/JR0lMCUlJTglQiX7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPswAAD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPswAAD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPswYCRhJGIkYyRkJGUkZiRnJGgkaSRqJGskbCRtJG4kbyRwJHEkciRzJGAhYSFiIWMhZCFlIWYhZyFoIWkh+zBJMxQzIjNNMxgz" +
            "JzMDMzYzUTNXMw0zJjMjMyszSjM7M5wznTOeM44zjzPEM6Ez+zD7MPsw+zD7MPsw+zD7MHszAAAdMB8wFiHNMyEhpDKlMqYypzKoMjEyMjI5Mn4zfTN8M1Ii" +
            "YSIrIi4iESIaIqUiICIfIr8iNSIpIioi+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPswAAD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MJxOFlUDWj+WwFQbYShj9lkikHWEHINQeqpg4WMlbu1lZoSmgvWbk2gnV6Fl" +
            "cWKbW9BZe4b0mGJ9vn2OmxZin3y3iIlbtV4JY5dmSGjHlY2XT2flTgpPTU+dT0lQ8lY3WdRZAVoJXN9gD2FwYRNmBWm6cE91cHX7ea19733DgA6EY4gCi1WQ" +
            "epA7U5VOpU7fV7KAwZDveABO8ViibjiQMnoog4uCL5xBUXBTvVThVOBW+1kVX/KY623kgC2FYpZwlqCW+5cLVPNTh1vPcL1/wo/olm9TXJ26ehFOk3j8gSZu" +
            "GFYEVR1rGoU7nOVZqVNmbdx0j5VCVpFOS5Dylk+DDJnhU7ZVMFtxXyBm82YEaDhs82wpbVt0yHZOejSY8YJbiGCK7ZKybat1ynbFmaZgAYuKjbKVjmmtU4ZR" +
            "AAASVzBYRFm0W/ZeKGCpY/Rjv2wUb45wFHFZcdVxP3MBfnaC0YKXhWCQW5IbnWlYvGVabCV1+VEuWWVZgF/cX7xi+mUqaidrtGuLc8F/VoksnQ6dxJ6hXJZs" +
            "e4MEUUtctmHGgXZoYXJZTvpPeFNpYCluT3rzlwtOFlPuTlVPPU+hT3NPoFLvUwlWD1nBWrZb4VvReYdmnGe2Z0xrs2xrcMJzjXm+eTx6h3uxgtuCBIN3g++D" +
            "04Nmh7KKKVaojOaPTpAel4qGxE/oXBFiWXI7deWBvYL+hsCMxZYTmdWZy04aT+OJ3lZKWMpY+17rXypglGBiYNBhEmLQYjllQZtmZrBod21wcEx1hnZ1faWC" +
            "+YeLlY6WnYzxUb5SFlmzVLNbFl1oYYJpr22NeMuEV4hyiqeTuJpsbaiZ2YajV/9nzoYOkoNSh1YEVNNe4WK5ZDxoOGi7a3JzunhrepqJ0olrjQOP7ZCjlZSW" +
            "aZdmW7NcfWlNmE6Ym2MgeytqAAB/arZoDZxfb3JSnVVwYOxiO20HbtFuW4QQiUSPFE45nPZTG2k6aoSXKmhcUcN6soTckYyTW1YonSJoBYMxhKV8CFLFguZ0" +
            "fk6DT6BR0lsKUthS51L7XZpVKljmWYxbmFvbW3JeeV6jYB9hY2G+YdtjYmXRZ1No+mg+a1NrV2wib5dvRW+wdBh143YLd/96oXshfOl9Nn/wf52AZoKeg7OJ" +
            "zIqrjISQUZSTlZGVopVlltOXKJkYgjhOK1S4XMxdqXNMdjx3qVzrfwuNwZYRmFSYWJgBTw5PcVOcVWhW+ldHWQlbxFuQXAxefl7MX+5jOmfXZeJlH2fLaMRo" +
            "X2owXsVrF2x9bH91SHljWwB6AH29X4+JGIq0jHeNzI4dj+KYDpo8m4BOfVAAUZNZnFsvYoBi7GQ6a6BykXVHeal/+4e8inCLrGPKg6CXCVQDVKtVVGhYanCK" +
            "J3h1Z82edFOiWxqBUIYGkBhORU7HThFPylM4VK5bE18lYFFlAAA9Z0JscmzjbHhwA3R2eq56CHsaff58Zn3nZVtyu1NFXOhd0mLgYhljIG5ahjGK3Y34kgFv" +
            "pnlam6hOq06sTptPoE/RUEdR9npxUfZRVFMhU39T61OsVYNY4Vw3X0pfL2BQYG1gH2NZZUtqwWzCcu1y73f4gAWBCIJOhfeQ4ZP/l1eZWprwTt1RLVyBZm1p" +
            "QFzyZnVpiXNQaIF8xVDkUkdX/l0mk6RlI2s9azR0gXm9eUt7yn25gsyDf4hfiTmL0Y/RkR9UgJJdTjZQ5VM6U9dylnPpd+aCr47GmciZ0pl3URphXoawVXp6" +
            "dlDTW0eQhZYyTttq55FRXEhcmGOfepNsdJdhj6p6inGIloJ8F2hwflFobJPyUhtUq4UTiqR/zY7hkGZTiIhBecJPvlARUkRRU1UtV+pzi1dRWWJfhF91YHZh" +
            "Z2GpYbJjOmRsZW9mQmgTbmZ1PXr7fEx9mX1Lfmt/DoNKg82GCIpjimaL/Y4amI+duILOj+ibAACHUh9ig2TAb5mWQWiRUCBremxUb3R6UH1AiCOKCGf2TjlQ" +
            "JlBlUHxROFJjUqdVD1cFWMxa+l6yYfhh82JyYxxpKWp9cqxyLnMUeG94eX0Md6mAi4kZi+KM0o5jkHWTepZVmBOaeJ5DUZ9Ts1N7XiZfG26QboRz/nNDfTeC" +
            "AIr6ilCWTk4LUORTfFT6VtFZZFvxXateJ184YkVlr2dWbtByyny0iKGA4YDwg06Gh4rojTeSx5ZnmBOflE6STg1PSFNJVD5UL1qMX6Ffn2CnaI5qWnSBeJ6K" +
            "pIp3i5CRXk7Jm6ROfE+vTxlQFlBJUWxRn1K5Uv5SmlPjUxFUDlSJVVFXold9WVRbXVuPW+Vd5133XXheg16aXrdeGF9SYExhl2LYYqdjO2UCZkNm9GZtZyFo" +
            "l2jLaV9sKm1pbS9unW4ydYd2bHg/euB8BX0YfV59sX0VgAOAr4CxgFSBj4EqglKDTIhhiBuLooz8jMqQdZFxkj94/JKklU2WAAAFmJmZ2Jo7nVtSq1L3UwhU" +
            "1Vj3YuBvaoxfj7meS1E7UkpU/VZAeneRYJ3SnkRzCW9wgRF1/V/aYKia23K8j2RrA5jKTvBWZFe+WFpaaGDHYQ9mBmY5aLFo923VdTp9boJCm5tOUE/JUwZV" +
            "b13mXe5d+2eZbHN0AnhQipaT34hQV6deK2O1UKxQjVEAZ8lUXli7WbBbaV9NYqFjPWhzawhufXDHkYByFXgmeG15jmUwfdyDwYgJj5uWZFIoV1Bnan+hjLRR" +
            "QlcqljpYimm0gLJUDl38V5V4+p1cT0pSi1Q+ZChmFGf1Z4R6VnsifS+TXGitmzl7GVOKUTdS31v2Yq5k5mQtZ7prqYXRlpB21ptMYwaTq5u/dlJmCU6YUMJT" +
            "cVzoYJJkY2VfaOZxynMjdZd7gn6VhoOL24x4kRCZrGWrZotr1U7UTjpPf086UvhT8lPjVdtW61jLWclZ/1lQW01cAl4rXtdfHWAHYy9lXFuvZb1l6GWdZ2Jr" +
            "AAB7aw9sRXNJecF5+HwZfSt9ooACgfOBloleimmKZoqMiu6Kx4zcjMyW/Jhva4tOPE+NT1BRV1v6W0hhAWNCZiFry267bD5yvXTUdcF4OnkMgDOA6oGUhJ6P" +
            "UGx/ng9fWIsrnfp6+I6NW+uWA07xU/dXMVnJWqRbiWB/bgZvvnXqjJ9bAIXge3JQ9GedgmFcSoUefg6CmVEEXGhjZo2cZW5xPnkXfQWAHYvKjm6Qx4aqkB9Q" +
            "+lI6XFNnfHA1ckyRyJErk+WCwlsxX/lgO07WU4hbS2IxZ4pr6XLgcy56a4GjjVKRlpkSUddTalT/W4hjOWqsfQCX2lbOU2hUl1sxXN5d7k8BYf5iMm3Aect5" +
            "Qn1NftJ/7YEfgpCERohyiZCLdI4vjzGQS5FskcaWnJHATk9PRVFBU5NfDmLUZ0FsC25jcyZ+zZGDktRTGVm/W9FtXXkufpt8flifcfpRU4jwj8pP+1wlZqx3" +
            "43ocgv+ZxlGqX+xlb2mJa/NtAACWbmRv/nYUfeFddZCHkQaY5lEdUkBikWbZZhputl7SfXJ/+GavhfeF+IqpUtlTc1mPXpBfVWDkkmSWt1AfUd1SIFNHU+xT" +
            "6FRGVTFVF1ZoWb5ZPFq1WwZcD1wRXBpchF6KXuBecF9/YoRi22KMY3djB2YMZi1mdmZ+Z6JoH2o1arxsiG0JblhuPHEmcWdxx3UBd114AXllefB54HoRe6d8" +
            "OX2WgNaDi4RJhV2I84gfijyKVIpzimGM3oykkWaSfpMYlJyWmJcKTghOHk5XTpdRcFLOVzRYzFgiWzhexWD+ZGFnVmdEbbZyc3VjeriEcou4kSCTMVb0V/6Y" +
            "7WINaZZr7XFUfneAcoLmid+YVYexjztcOE/hT7VPB1UgWt1b6VvDX05hL2OwZUtm7mibaXht8W0zdbl1H3deeeZ5M33jga+CqoWqiTqKq46bjzKQ3ZEHl7pO" +
            "wU4DUnVY7FgLXBp1PVxOgQqKxY9jlm2XJXvPigiYYpHzVqhTAAAXkDlUglclXqhjNGyKcGF3i3zgf3CIQpBUkRCTGJOPll50xJoHXWldcGWiZ6iN25ZuY0ln" +
            "GWnFgxeYwJb+iIRvemT4WxZOLHBddS9mxFE2UuJS01mBXydgEGI/ZXRlH2Z0ZvJoFmhjawVucnIfddt2vnxWgPBY/Yh/iaCKk4rLih2QkpFSl1mXiWUOegaB" +
            "u5YtXtxgGmKlZRRmkGfzd016TXw+fgqBrIxkjeGNX46peAdS2WKlY0JkmGItioN6wHusiuqWdn0MgkmH2U5IUUNTYFOjWwJcFlzdXSZiR2KwZBNoNGjJbEVt" +
            "F23TZ1xvTnF9cctlf3qte9p9Sn6of3qBG4I5gqaFborOjPWNeJB3kK2SkZKDla6bTVKEVThvNnFoUYV5VX6zgc58TFZRWKhcqmP+Zv1mWmnZco91jnUOeVZ5" +
            "33mXfCB9RH0HhjSKO5ZhkCCf51B1UsxT4lMJUKpV7lhPWT1yi1tkXB1T42DzYFxjg2M/Y7tjAADNZOll+WbjXc1p/WkVb+VxiU7pdfh2k3rffM99nH1hgEmD" +
            "WINshLyE+4XFiHCNAZBtkJeTHJcSms9Ql1iOYdOBNYUIjSCQw090UEdSc1NvYEljX2csbrONH5DXT15cyozPZZp9UlOWiHZRw2NYW2tbClwNZFFnXJDWThpZ" +
            "KllwbFGKPlUVWKVZ8GBTYsFnNYJVaUCWxJkomlNPBlj+WxCAsVwvXoVfIGBLYTRi/2bwbN5uzoB/gdSCi4i4jACQLpCKltue25vjTvBTJ1kse42RTJj5nd1u" +
            "J3BTU0RVhVtYYp5i02KibO9vInQXijiUwW/+ijiD51H4hupT6VNGT1SQsI9qWTGB/V3qer+P2mg3jPhySJw9arCKOU5YUwZWZlfFYqJj5mVOa+FtW26tcO13" +
            "73qqe7t9PYDGgMuGlYpbk+NWx1g+X61llmaAarVrN3XHiiRQ5XcwVxtfZWB6ZmBs9HUaem5/9IEYh0WQs5nJe1x1+XpRe8SEAAAQkOl5kno2g+FaQHctTvJO" +
            "mVvgX71iPGbxZ+hsa4Z3iDuKTpHzktCZF2omcCpz54JXhK+MAU5GUctRi1X1WxZeM16BXhRfNV9rX7Rf8mERY6JmHWdub1JyOnU6d3SAOYF4gXaHv4rcioWN" +
            "842akneVApjlnMVSV2P0dhVniGzNc8OMrpNzliVtnFgOacxp/Y+ak9t1GpBaWAJotGP7aUNPLG/YZ7uPJoW0fVSTP2lwb2pX91gsWyx9KnIKVOORtJ2tTk5P" +
            "XFB1UENSnoxIVCRYmlsdXpVerV73Xh9fjGC1Yjpj0GOvaEBsh3iOeQt64H1HggKK5opEjhOQuJAtkdiRDp/lbFhk4mR1ZfRuhHYbe2mQ0ZO6bvJUuV+kZE2P" +
            "7Y9EknhRa1gpWVVcl177bY9+HHW8jOKOW5i5cB1Pv2uxbzB1+5ZOURBUNVhXWKxZYFySX5dlXGchbnt234PtjBSQ/ZBNkyV4OniqUqZeH1d0WRJgElBaUaxR" +
            "AADNUQBSEFVUWFhYV1mVW/Zci128YJViLWRxZ0NovGjfaNd22G1vbpttb3DIcVNf2HV3eUl7VHtSe9Z8cX0wUmOEaYXkhQ6KBItGjA+OA5APkBmUdpYtmDCa" +
            "2JXNUNVSDFQCWA5cp2GeZB5ts3flevSABIRTkIWS4FwHnT9Tl1+zX5xteXJjd7955HvSa+xyrYoDaGFq+FGBejRpSlz2nOuCxVtJkR5weFZvXMdgZmWMbFqM" +
            "QZATmFFUx2YNkkhZo5CFUU1O6lGZhQ6LWHB6Y0uTYmm0mQR+d3VXU2Bp347jll1sjE48XBBf6Y8CU9GMiYB5hv9e5WVzTmVRglk/XO6X+06KWc1fjYrhb7B5" +
            "YnnnW3GEK3OxcXRe9V97Y5pkw3GYfENO/F5LTtxXolapYMNvDX39gDOBv4Gyj5eJpIb0XYpirWSHiXdn4mw+bTZ0NHhGWnV/rYKsmfNPw17dYpJjV2VvZ8N2" +
            "THLMgLqAKY9NkQ1Q+VeSWoVoAABzaWRx/XK3jPJY4IxqlhmQf4fkeed3KYQvT2VSWlPNYs9nymx9dpR7lXw2goSF64/dZiBvBnIbfquDwZmmnv1RsXtyeLh7" +
            "h4BIe+hqYV6MgFF1YHVrUWKSjG56dpeR6poQT3B/nGJPe6WV6Zx6VllY5Ia8ljRPJFJKU81T21MGXixkkWV/Zz5sTmxIcq9y7XNUdUF+LILphamMxHvGkWlx" +
            "EpjvmD1jaWZqdeR20HhDhe6GKlNRUyZUg1mHXnxfsmBJYnliq2KQZdRrzGyyda52kXjYect9d3+lgKuIuYq7jH+QXpfbmAtqOHyZUD5crl+HZ9hrNXQJd45/" +
            "O5/KZxd6OVOLde2aZl+dgfGDmIA8X8VfYnVGezyQZ2jrWZtaEH1+diyL9U9qXxlqN2wCb+J0aHloiFWKeYzfXs9jxXXSedeCKJPykpyE7YYtnMFUbF+MZVxt" +
            "FXCnjNOMO5hPZfZ0DU7YTuBXK1lmWsxbqFEDXpxeFmB2YndlAACnZW5mbm02ciZ7UIGagZmCXIugjOaMdI0clkSWrk+rZGZrHoJhhGqF6JABXFNpqJh6hFeF" +
            "D09vUqlfRV4NZ495eYEHiYaJ9W0XX1ViuGzPTmlykpsGUjtUdFazWKRhbmIacW5ZiXzefBt98JaHZV6AGU51T3VRQFhjXnNeCl/EZyZOPYWJlVuWc3wBmPtQ" +
            "wVhWdqd4JVKldxGFhntPUAlZR3LHe+h9uo/Uj02Qv0/JUilaAV+tl91PF4LqkgNXVWNpayt13IgUj0J631KTWFVhCmKuZs1rP3zpgyNQ+E8FU0ZUMVhJWZ1b" +
            "8FzvXCldll6xYmdjPmW5ZQtn1WzhbPlwMngrft6As4IMhOyEAocSiSqKSoymkNKS/ZjznGydT06hTo1QVlJKV6hZPV7YX9lfP2K0Zhtn0GfSaJJRIX2qgKiB" +
            "AIuMjL+MfpIyliBULJgXU9VQXFOoWLJkNGdncmZ3RnrmkcNSoWyGawBYTF5UWSxn+3/hUcZ2AABpZOh4VJu7nstXuVknZppnzmvpVNlpVV6cgZVnqpv+Z1Kc" +
            "XWimTuNPyFO5Yitnq2zEj61PbX6/ngdOYmGAbitvE4VzVCpnRZvzXZV7rFzGWxyHSm7RhBR6CIGZWY18EWwgd9lSIlkhcV9y23cnl2GdC2l/WhhapVENVH1U" +
            "DmbfdvePmJL0nOpZXXLFbk1RyWi/fex9Ype6nnhkIWoCg4RZX1vbaxtz8nayfReAmYQyUShn2Z7udmJn/1IFmSRcO2J+fLCMT1W2YAt9gJUBU19OtlEcWTpy" +
            "NoDOkSVf4neEU3lfBH2shTOKjY5Wl/NnroVTlAlhCGG5bFJ27Yo4jy9VUU8qUcdSy1OlW31eoGCCYdZjCWfaZ2dujG02czdzMXVQedWImIpKkJGQ9ZDElo2H" +
            "FVmITllPDk6Jij+PEJitUHxellm5W7he2mP6Y8Fk3GZKadhpC222bpRxKHWveop/AIBJhMmEgYkhiwqOZZB9lgqZfmGRYjJrAACDbHRtzH/8f8BthX+6h/iI" +
            "ZWexgzyY95YbbWF9PYRqkXFOdVNQXQRr62/NhS2Gp4kpUg9UZVxOZ6hoBnSDdOJ1z4jhiMyR4pZ4lotfh3PLek6EoGNldYlSQW2cbgl0WXVreJJ8hpbceo2f" +
            "tk9uYcVlXIaGTq5O2lAhTsxR7luZZYFovG0fc0J2rXcceud8b4LSinyQz5F1lhiYm1LRfStQmFOXZ8tt0HEzdOiBKo+jllecn55gdEFYmW0vfV6Y5E42T4tP" +
            "t1GxUrpdHGCyczx504I0kreW9pYKl5eeYp+mZnRrF1KjUshwwojJXktgkGEjb0lxPnz0fW+A7oQjkCyTQlRvm9NqiXDCjO+NMpe0UkFayl4EXxdnfGmUaWpt" +
            "D29icvxy7XsBgH6AS4fOkG1Rk56EeYuAMpPWii1QjFRximprxIwHgdFgoGfynZlOmE4QnGuKwYVohQBpfm6XeFWB+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "AAD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MAxfEE4VTipOMU42TjxOP05CTlZOWE6CToVO" +
            "a4yKThKCDV+OTp5On06gTqJOsE6zTrZOzk7NTsROxk7CTtdO3k7tTt9O904JT1pPME9bT11PV09HT3ZPiE+PT5hPe09pT3BPkU9vT4ZPlk8YUdRP30/OT9hP" +
            "20/RT9pP0E/kT+VPGlAoUBRQKlAlUAVQHE/2TyFQKVAsUP5P708RUAZQQ1BHUANnVVBQUEhQWlBWUGxQeFCAUJpQhVC0ULJQyVDKULNQwlDWUN5Q5VDtUONQ" +
            "7lD5UPVQCVEBUQJRFlEVURRRGlEhUTpRN1E8UTtRP1FAUVJRTFFUUWJR+HppUWpRblGAUYJR2FaMUYlRj1GRUZNRlVGWUaRRplGiUalRqlGrUbNRsVGyUbBR" +
            "tVG9UcVRyVHbUeBRVYbpUe1RAADwUfVR/lEEUgtSFFIOUidSKlIuUjNSOVJPUkRSS1JMUl5SVFJqUnRSaVJzUn9SfVKNUpRSklJxUohSkVKoj6ePrFKtUrxS" +
            "tVLBUs1S11LeUuNS5lLtmOBS81L1UvhS+VIGUwhTOHUNUxBTD1MVUxpTI1MvUzFTM1M4U0BTRlNFUxdOSVNNU9ZRXlNpU25TGFl7U3dTglOWU6BTplOlU65T" +
            "sFO2U8NTEnzZlt9T/Gbuce5T6FPtU/pTAVQ9VEBULFQtVDxULlQ2VClUHVROVI9UdVSOVF9UcVR3VHBUklR7VIBUdlSEVJBUhlTHVKJUuFSlVKxUxFTIVKhU" +
            "q1TCVKRUvlS8VNhU5VTmVA9VFFX9VO5U7VT6VOJUOVVAVWNVTFUuVVxVRVVWVVdVOFUzVV1VmVWAVa9UilWfVXtVflWYVZ5VrlV8VYNVqVWHVahV2lXFVd9V" +
            "xFXcVeRV1FUUVvdVFlb+Vf1VG1b5VU5WUFbfcTRWNlYyVjhWAABrVmRWL1ZsVmpWhlaAVopWoFaUVo9WpVauVrZWtFbCVrxWwVbDVsBWyFbOVtFW01bXVu5W" +
            "+VYAV/9WBFcJVwhXC1cNVxNXGFcWV8dVHFcmVzdXOFdOVztXQFdPV2lXwFeIV2FXf1eJV5NXoFezV6RXqlewV8NXxlfUV9JX01cKWNZX41cLWBlYHVhyWCFY" +
            "YlhLWHBYwGtSWD1YeViFWLlYn1irWLpY3li7WLhYrljFWNNY0VjXWNlY2FjlWNxY5FjfWO9Y+lj5WPtY/Fj9WAJZClkQWRtZpmglWSxZLVkyWThZPlnSelVZ" +
            "UFlOWVpZWFliWWBZZ1lsWWlZeFmBWZ1ZXk+rT6NZslnGWehZ3FmNWdlZ2lklWh9aEVocWglaGlpAWmxaSVo1WjZaYlpqWppavFq+Wstawlq9WuNa11rmWula" +
            "1lr6WvtaDFsLWxZbMlvQWipbNls+W0NbRVtAW1FbVVtaW1tbZVtpW3Bbc1t1W3hbiGV6W4BbAACDW6ZbuFvDW8dbyVvUW9Bb5FvmW+Jb3lvlW+tb8Fv2W/Nb" +
            "BVwHXAhcDVwTXCBcIlwoXDhcOVxBXEZcTlxTXFBcT1xxW2xcblxiTnZceVyMXJFclFybWatcu1y2XLxct1zFXL5cx1zZXOlc/Vz6XO1cjF3qXAtdFV0XXVxd" +
            "H10bXRFdFF0iXRpdGV0YXUxdUl1OXUtdbF1zXXZdh12EXYJdol2dXaxdrl29XZBdt128XcldzV3TXdJd1l3bXetd8l31XQteGl4ZXhFeG142XjdeRF5DXkBe" +
            "Tl5XXlReX15iXmReR151XnZeel68nn9eoF7BXsJeyF7QXs9e1l7jXt1e2l7bXuJe4V7oXule7F7xXvNe8F70Xvhe/l4DXwlfXV9cXwtfEV8WXylfLV84X0Ff" +
            "SF9MX05fL19RX1ZfV19ZX2FfbV9zX3dfg1+CX39fil+IX5Ffh1+eX5lfmF+gX6hfrV+8X9Zf+1/kX/hf8V/dX7Ng/18hYGBgAAAZYBBgKWAOYDFgG2AVYCtg" +
            "JmAPYDpgWmBBYGpgd2BfYEpgRmBNYGNgQ2BkYEJgbGBrYFlggWCNYOdgg2CaYIRgm2CWYJdgkmCnYItg4WC4YOBg02C0YPBfvWDGYLVg2GBNYRVhBmH2YPdg" +
            "AGH0YPpgA2EhYftg8WANYQ5hR2E+YShhJ2FKYT9hPGEsYTRhPWFCYURhc2F3YVhhWWFaYWthdGFvYWVhcWFfYV1hU2F1YZlhlmGHYaxhlGGaYYphkWGrYa5h" +
            "zGHKYclh92HIYcNhxmG6YctheX/NYeZh42H2Yfph9GH/Yf1h/GH+YQBiCGIJYg1iDGIUYhtiHmIhYipiLmIwYjJiM2JBYk5iXmJjYltiYGJoYnxigmKJYn5i" +
            "kmKTYpZi1GKDYpRi12LRYrtiz2L/YsZi1GTIYtxizGLKYsJix2KbYsliDGPuYvFiJ2MCYwhj72L1YlBjPmNNYxxkT2OWY45jgGOrY3Zjo2OPY4ljn2O1Y2tj" +
            "AABpY75j6WPAY8Zj42PJY9Jj9mPEYxZkNGQGZBNkJmQ2ZB1lF2QoZA9kZ2RvZHZkTmQqZZVkk2SlZKlkiGS8ZNpk0mTFZMdku2TYZMJk8WTnZAmC4GThZKxi" +
            "42TvZCxl9mT0ZPJk+mQAZf1kGGUcZQVlJGUjZStlNGU1ZTdlNmU4ZUt1SGVWZVVlTWVYZV5lXWVyZXhlgmWDZYqLm2WfZatlt2XDZcZlwWXEZcxl0mXbZdll" +
            "4GXhZfFlcmcKZgNm+2VzZzVmNmY0ZhxmT2ZEZklmQWZeZl1mZGZnZmhmX2ZiZnBmg2aIZo5miWaEZphmnWbBZrlmyWa+ZrxmxGa4ZtZm2mbgZj9m5mbpZvBm" +
            "9Wb3Zg9nFmceZyZnJ2c4ly5nP2c2Z0FnOGc3Z0ZnXmdgZ1lnY2dkZ4lncGepZ3xnameMZ4tnpmehZ4Vnt2fvZ7Rn7GezZ+lnuGfkZ95n3WfiZ+5nuWfOZ8Zn" +
            "52ecah5oRmgpaEBoTWgyaE5oAACzaCtoWWhjaHdof2ifaI9orWiUaJ1om2iDaK5quWh0aLVooGi6aA9pjWh+aAFpymgIadhoImkmaeFoDGnNaNRo52jVaDZp" +
            "EmkEaddo42glaflo4GjvaChpKmkaaSNpIWnGaHlpd2lcaXhpa2lUaX5pbmk5aXRpPWlZaTBpYWleaV1pgWlqabJprmnQab9pwWnTab5pzmnoW8pp3Wm7acNp" +
            "p2kuapFpoGmcaZVptGneaehpAmobav9pCmv5afJp52kFarFpHmrtaRRq62kKahJqwWojahNqRGoManJqNmp4akdqYmpZamZqSGo4aiJqkGqNaqBqhGqiaqNq" +
            "l2oXhrtqw2rCarhqs2qsat5q0Wrfaqpq2mrqavtqBWsWhvpqEmsWazGbH2s4azdr3HY5a+6YR2tDa0lrUGtZa1RrW2tfa2FreGt5a39rgGuEa4NrjWuYa5Vr" +
            "nmuka6prq2uva7JrsWuza7drvGvGa8tr02vfa+xr62vza+9rAAC+nghsE2wUbBtsJGwjbF5sVWxibGpsgmyNbJpsgWybbH5saGxzbJJskGzEbPFs02y9bNds" +
            "xWzdbK5ssWy+bLps22zvbNls6mwfbU2INm0rbT1tOG0ZbTVtM20SbQxtY22TbWRtWm15bVltjm2VbeRvhW35bRVuCm61bcdt5m24bcZt7G3ebcxt6G3SbcVt" +
            "+m3ZbeRt1W3qbe5tLW5ubi5uGW5ybl9uPm4jbmtuK252bk1uH25DbjpuTm4kbv9uHW44boJuqm6Ybslut27Tbr1ur27EbrJu1G7Vbo9upW7Cbp9uQW8Rb0xw" +
            "7G74bv5uP2/ybjFv724yb8xuPm8Tb/duhm96b3hvgW+Ab29vW2/zb21vgm98b1hvjm+Rb8JvZm+zb6NvoW+kb7lvxm+qb99v1W/sb9Rv2G/xb+5v228JcAtw" +
            "+m8RcAFwD3D+bxtwGnB0bx1wGHAfcDBwPnAycFFwY3CZcJJwr3DxcKxwuHCzcK5w33DLcN1wAADZcAlx/XAccRlxZXFVcYhxZnFicUxxVnFscY9x+3GEcZVx" +
            "qHGscddxuXG+cdJxyXHUcc5x4HHscedx9XH8cflx/3ENchByG3Ioci1yLHIwcjJyO3I8cj9yQHJGcktyWHJ0cn5ygnKBcodyknKWcqJyp3K5crJyw3LGcsRy" +
            "znLScuJy4HLhcvly93IPUBdzCnMccxZzHXM0cy9zKXMlcz5zTnNPc9ieV3Nqc2hzcHN4c3Vze3N6c8hzs3POc7tzwHPlc+5z3nOidAV0b3QldPhzMnQ6dFV0" +
            "P3RfdFl0QXRcdGl0cHRjdGp0dnR+dIt0nnSndMp0z3TUdPFz4HTjdOd06XTudPJ08HTxdPh093QEdQN1BXUMdQ51DXUVdRN1HnUmdSx1PHVEdU11SnVJdVt1" +
            "RnVadWl1ZHVndWt1bXV4dXZ1hnWHdXR1inWJdYJ1lHWadZ11pXWjdcJ1s3XDdbV1vXW4dbx1sXXNdcp10nXZdeN13nX+df91AAD8dQF28HX6dfJ183ULdg12" +
            "CXYfdid2IHYhdiJ2JHY0djB2O3ZHdkh2RnZcdlh2YXZidmh2aXZqdmd2bHZwdnJ2dnZ4dnx2gHaDdoh2i3aOdpZ2k3aZdpp2sHa0drh2uXa6dsJ2zXbWdtJ2" +
            "3nbhduV253bqdi+G+3YIdwd3BHcpdyR3HncldyZ3G3c3dzh3R3dad2h3a3dbd2V3f3d+d3l3jneLd5F3oHeed7B3tne5d793vHe9d7t3x3fNd9d32nfcd+N3" +
            "7nf8dwx4EngmeSB4KnlFeI54dHiGeHx4mniMeKN4tXiqeK940XjGeMt41Hi+eLx4xXjKeOx453jaeP149HgHeRJ5EXkZeSx5K3lAeWB5V3lfeVp5VXlTeXp5" +
            "f3mKeZ15p3lLn6p5rnmzebl5unnJedV553nseeF543kIeg16GHoZeiB6H3qAeTF6O3o+ejd6Q3pXekl6YXpieml6nZ9wenl6fXqIepd6lXqYepZ6qXrIerB6" +
            "AAC2esV6xHq/eoOQx3rKes16z3rVetN62Xraet164XrieuZ67XrwegJ7D3sKewZ7M3sYexl7Hns1eyh7NntQe3p7BHtNewt7THtFe3V7ZXt0e2d7cHtxe2x7" +
            "bnude5h7n3uNe5x7mnuLe5J7j3tde5l7y3vBe8x7z3u0e8Z73XvpexF8FHzme+V7YHwAfAd8E3zze/d7F3wNfPZ7I3wnfCp8H3w3fCt8PXxMfEN8VHxPfEB8" +
            "UHxYfF98ZHxWfGV8bHx1fIN8kHykfK18onyrfKF8qHyzfLJ8sXyufLl8vXzAfMV8wnzYfNJ83HzifDub73zyfPR89nz6fAZ9An0cfRV9Cn1FfUt9Ln0yfT99" +
            "NX1GfXN9Vn1OfXJ9aH1ufU99Y32TfYl9W32PfX19m326fa59o321fcd9vX2rfT1+on2vfdx9uH2ffbB92H3dfeR93n37ffJ94X0Ffgp+I34hfhJ+MX4ffgl+" +
            "C34ifkZ+Zn47fjV+OX5Dfjd+AAAyfjp+Z35dflZ+Xn5Zflp+eX5qfml+fH57foN+1X19fq6Pf36Ifol+jH6SfpB+k36UfpZ+jn6bfpx+OH86f0V/TH9Nf05/" +
            "UH9Rf1V/VH9Yf19/YH9of2l/Z394f4J/hn+Df4h/h3+Mf5R/nn+df5p/o3+vf7J/uX+uf7Z/uH9xi8V/xn/Kf9V/1H/hf+Z/6X/zf/l/3JgGgASAC4ASgBiA" +
            "GYAcgCGAKIA/gDuASoBGgFKAWIBagF+AYoBogHOAcoBwgHaAeYB9gH+AhICGgIWAm4CTgJqArYCQUayA24DlgNmA3YDEgNqA1oAJge+A8YAbgSmBI4EvgUuB" +
            "i5ZGgT6BU4FRgfyAcYFugWWBZoF0gYOBiIGKgYCBgoGggZWBpIGjgV+Bk4GpgbCBtYG+gbiBvYHAgcKBuoHJgc2B0YHZgdiByIHagd+B4IHngfqB+4H+gQGC" +
            "AoIFggeCCoINghCCFoIpgiuCOIIzgkCCWYJYgl2CWoJfgmSCAABigmiCaoJrgi6CcYJ3gniCfoKNgpKCq4KfgruCrILhguOC34LSgvSC84L6gpODA4P7gvmC" +
            "3oIGg9yCCYPZgjWDNIMWgzKDMYNAgzmDUINFgy+DK4MXgxiDhYOag6qDn4Oig5aDI4OOg4eDioN8g7WDc4N1g6CDiYOog/SDE4Trg86D/YMDhNiDC4TBg/eD" +
            "B4Tgg/KDDYQihCCEvYM4hAaF+4NthCqEPIRahYSEd4RrhK2EboSChGmERoQshG+EeYQ1hMqEYoS5hL+En4TZhM2Eu4TahNCEwYTGhNaEoYQhhf+E9IQXhRiF" +
            "LIUfhRWFFIX8hECFY4VYhUiFQYUChkuFVYWAhaSFiIWRhYqFqIVthZSFm4XqhYeFnIV3hX6FkIXJhbqFz4W5hdCF1YXdheWF3IX5hQqGE4YLhv6F+oUGhiKG" +
            "GoYwhj+GTYZVTlSGX4ZnhnGGk4ajhqmGqoaLhoyGtoavhsSGxoawhsmGI4irhtSG3obphuyGAADfhtuG74YShwaHCIcAhwOH+4YRhwmHDYf5hgqHNIc/hzeH" +
            "O4clhymHGodgh1+HeIdMh06HdIdXh2iHbodZh1OHY4dqhwWIooefh4KHr4fLh72HwIfQh9aWq4fEh7OHx4fGh7uH74fyh+CHD4gNiP6H9of3hw6I0ocRiBaI" +
            "FYgiiCGIMYg2iDmIJ4g7iESIQohSiFmIXohiiGuIgYh+iJ6IdYh9iLWIcoiCiJeIkoiuiJmIooiNiKSIsIi/iLGIw4jEiNSI2IjZiN2I+YgCifyI9IjoiPKI" +
            "BIkMiQqJE4lDiR6JJYkqiSuJQYlEiTuJNok4iUyJHYlgiV6JZolkiW2JaolviXSJd4l+iYOJiImKiZOJmImhiamJpomsia+Jsom6ib2Jv4nAidqJ3IndieeJ" +
            "9In4iQOKFooQigyKG4odiiWKNopBiluKUopGikiKfIptimyKYoqFioKKhIqoiqGKkYqliqaKmoqjisSKzYrCitqK64rziueKAADkivGKFIvgiuKK94reituK" +
            "DIsHixqL4YoWixCLF4sgizOLq5cmiyuLPosoi0GLTItPi06LSYtWi1uLWotri1+LbItvi3SLfYuAi4yLjouSi5OLlouZi5qLOoxBjD+MSIxMjE6MUIxVjGKM" +
            "bIx4jHqMgoyJjIWMioyNjI6MlIx8jJiMHWKtjKqMvYyyjLOMroy2jMiMwYzkjOOM2oz9jPqM+4wEjQWNCo0HjQ+NDY0QjU6fE43NjBSNFo1njW2NcY1zjYGN" +
            "mY3Cjb6Nuo3PjdqN1o3MjduNy43qjeuN343jjfyNCI4Jjv+NHY4ejhCOH45CjjWOMI40jkqOR45JjkyOUI5IjlmOZI5gjiqOY45VjnaOco58joGOh46FjoSO" +
            "i46KjpOOkY6UjpmOqo6hjqyOsI7GjrGOvo7FjsiOy47bjuOO/I77juuO/o4KjwWPFY8SjxmPE48cjx+PG48MjyaPM487jzmPRY9Cjz6PTI9Jj0aPTo9Xj1yP" +
            "AABij2OPZI+cj5+Po4+tj6+Pt4/aj+WP4o/qj++Ph5D0jwWQ+Y/6jxGQFZAhkA2QHpAWkAuQJ5A2kDWQOZD4j0+QUJBRkFKQDpBJkD6QVpBYkF6QaJBvkHaQ" +
            "qJZykIKQfZCBkICQipCJkI+QqJCvkLGQtZDikOSQSGLbkAKREpEZkTKRMJFKkVaRWJFjkWWRaZFzkXKRi5GJkYKRopGrka+RqpG1kbSRupHAkcGRyZHLkdCR" +
            "1pHfkeGR25H8kfWR9pEekv+RFJIskhWSEZJekleSRZJJkmSSSJKVkj+SS5JQkpySlpKTkpuSWpLPkrmSt5Lpkg+T+pJEky6TGZMikxqTI5M6kzWTO5Nck2CT" +
            "fJNuk1aTsJOsk62TlJO5k9aT15Pok+WT2JPDk92T0JPIk+STGpQUlBOUA5QHlBCUNpQrlDWUIZQ6lEGUUpRElFuUYJRilF6UapQpknCUdZR3lH2UWpR8lH6U" +
            "gZR/lIKVh5WKlZSVlpWYlZmVAACglaiVp5WtlbyVu5W5lb6VypX2b8OVzZXMldWV1JXWldyV4ZXlleKVIZYoli6WL5ZClkyWT5ZLlneWXJZell2WX5ZmlnKW" +
            "bJaNlpiWlZaXlqqWp5axlrKWsJa0lraWuJa5ls6Wy5bJls2WTYnclg2X1Zb5lgSXBpcIlxOXDpcRlw+XFpcZlySXKpcwlzmXPZc+l0SXRpdIl0KXSZdcl2CX" +
            "ZJdml2iX0lJrl3GXeZeFl3yXgZd6l4aXi5ePl5CXnJeol6aXo5ezl7SXw5fGl8iXy5fcl+2XT5/yl9969pf1lw+YDJg4mCSYIZg3mD2YRphPmEuYa5hvmHCY" +
            "cZh0mHOYqpivmLGYtpjEmMOYxpjpmOuYA5kJmRKZFJkYmSGZHZkemSSZIJksmS6ZPZk+mUKZSZlFmVCZS5lRmVKZTJlVmZeZmJmlma2Zrpm8md+Z25ndmdiZ" +
            "0Zntme6Z8ZnymfuZ+JkBmg+aBZrimRmaK5o3mkWaQppAmkOaAAA+mlWaTZpbmleaX5pimmWaZJppmmuaapqtmrCavJrAms+a0ZrTmtSa3prfmuKa45rmmu+a" +
            "65rumvSa8Zr3mvuaBpsYmxqbH5simyObJZsnmyibKZsqmy6bL5sym0SbQ5tPm02bTptRm1ibdJuTm4ObkZuWm5ebn5ugm6ibtJvAm8qbuZvGm8+b0ZvSm+Ob" +
            "4pvkm9Sb4Zs6nPKb8ZvwmxWcFJwJnBOcDJwGnAicEpwKnAScLpwbnCWcJJwhnDCcR5wynEacPpxanGCcZ5x2nHic55zsnPCcCZ0IneucA50GnSqdJp2vnSOd" +
            "H51EnRWdEp1BnT+dPp1GnUidXZ1enWSdUZ1QnVmdcp2JnYedq51vnXqdmp2knamdsp3EncGdu524nbqdxp3PncKd2Z3Tnfid5p3tne+d/Z0anhueHp51nnme" +
            "fZ6Bnoiei56MnpKelZ6Rnp2epZ6pnrieqp6tnmGXzJ7Ons+e0J7Untye3p7dnuCe5Z7onu+eAAD0nvae9575nvue/J79ngefCJ+3dhWfIZ8snz6fSp9Sn1Sf" +
            "Y59fn2CfYZ9mn2efbJ9qn3efcp92n5WfnJ+gny9Yx2lZkGR03FGZcfsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPswAAD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "AAD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPswin4ciUiTiJLchMlPu3AxZsho" +
            "+ZL7ZkVfKE7hTvxOAE8DTzlPVk+ST4pPmk+UT81PQFAiUP9PHlBGUHBQQlCUUPRQ2FBKUWRRnVG+UexRFVKcUqZSwFLbUgBTB1MkU3JTk1OyU91TDvqcVIpU" +
            "qVT/VIZVWVdlV6xXyFfHVw/6AAAQ+p5YslgLWVNZW1ldWWNZpFm6WVZbwFsvddhb7FseXKZculz1XCddU10R+kJdbV24Xbld0F0hXzRfZ1+3X95fXWCFYIpg" +
            "3mDVYCBh8mARYTdhMGGYYRNipmL1Y2BknWTOZE5lAGYVZjtmCWYuZh5mJGZlZldmWWYS+nNmmWagZrJmv2b6Zg5nKflmZ7tnUmjAZwFoRGjPaBP6aGkU+php" +
            "4mkwamtqRmpzan5q4mrkatZrP2xcbIZsb2zabARth21vbZZtrG3Pbfht8m38bTluXG4nbjxuv26Ib7Vv9W8FcAdwKHCFcKtwD3EEcVxxRnFHcRX6wXH+cbFy" +
            "vnIkcxb6d3O9c8lz1nPjc9JzB3T1cyZ0KnQpdC50YnSJdJ90AXVvdYJ2nHaedpt2pnYX+kZ3r1IheE54ZHh6eDB5GPoZ+hr6lHkb+pt50Xrnehz663qeex36" +
            "SH1cfbd9oH3WfVJ+R3+hfx76AYNig3+Dx4P2g0iEtIRThVmFAABrhR/6sIUg+iH6B4j1iBKKN4p5iqeKvorfiiL69opTi3+L8Iz0jBKNdo0j+s+OJPol+meQ" +
            "3pAm+hWRJ5HakdeR3pHtke6R5JHlkQaSEJIKkjqSQJI8kk6SWZJRkjmSZ5KnkneSeJLnkteS2ZLQkif61ZLgktOSJZMhk/uSKPoek/+SHZMCk3CTV5Okk8aT" +
            "3pP4kzGURZRIlJKV3Pkp+p2Wr5YzlzuXQ5dNl0+XUZdVl1eYZZgq+iv6J5ks+p6ZTprZmtyadZtym4+bsZu7mwCccJ1rnS36GZ7Rnvsw+zBwIXEhciFzIXQh" +
            "dSF2IXcheCF5IeL/5P8H/wL/+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPswAAD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPswAOAB4ALgA+AE4AXgBuAH4AjgCeAK4AvgDOAN4A7gD+AQ4BHgEuAT4BTgFeAW4BfgGOAZ4Brg" +
            "G+Ac4B3gHuAf4CDgIeAi4CPgJOAl4CbgJ+Ao4CngKuAr4CzgLeAu4C/gMOAx4DLgM+A04DXgNuA34DjgOeA64DvgPOA94D7gAAA/4EDgQeBC4EPgROBF4Ebg" +
            "R+BI4EngSuBL4EzgTeBO4E/gUOBR4FLgU+BU4FXgVuBX4FjgWeBa4FvgXOBd4F7gX+Bg4GHgYuBj4GTgZeBm4GfgaOBp4Grga+Bs4G3gbuBv4HDgceBy4HPg" +
            "dOB14Hbgd+B44HngeuB74HzgfeB+4H/ggOCB4ILgg+CE4IXghuCH4IjgieCK4IvgjOCN4I7gj+CQ4JHgkuCT4JTgleCW4JfgmOCZ4Jrgm+Cc4J3gnuCf4KDg" +
            "oeCi4KPgpOCl4Kbgp+Co4KngquCr4KzgreCu4K/gsOCx4LLgs+C04LXgtuC34LjgueC64LvgvOC94L7gv+DA4MHgwuDD4MTgxeDG4MfgyODJ4Mrgy+DM4M3g" +
            "zuDP4NDg0eDS4NPg1ODV4Nbg1+DY4Nng2uDb4Nzg3eDe4N/g4ODh4OLg4+Dk4OXg5uDn4Ojg6eDq4Ovg7ODt4O7g7+Dw4PHg8uDz4PTg9eD24Pfg+OD54Prg" +
            "AAD74Pzg/eD+4P/gAOEB4QLhA+EE4QXhBuEH4QjhCeEK4QvhDOEN4Q7hD+EQ4RHhEuET4RThFeEW4RfhGOEZ4RrhG+Ec4R3hHuEf4SDhIeEi4SPhJOEl4Sbh" +
            "J+Eo4SnhKuEr4SzhLeEu4S/hMOEx4TLhM+E04TXhNuE34TjhOeE64TvhPOE94T7hP+FA4UHhQuFD4UThReFG4UfhSOFJ4UrhS+FM4U3hTuFP4VDhUeFS4VPh" +
            "VOFV4VbhV+FY4VnhWuFb4VzhXeFe4V/hYOFh4WLhY+Fk4WXhZuFn4WjhaeFq4WvhbOFt4W7hb+Fw4XHhcuFz4XThdeF24XfheOF54Xrhe+F84X3hfuF/4YDh" +
            "geGC4YPhhOGF4Ybhh+GI4YnhiuGL4YzhjeGO4Y/hkOGR4ZLhk+GU4ZXhluGX4ZjhmeGa4ZvhnOGd4Z7hn+Gg4aHhouGj4aThpeGm4afhqOGp4arhq+Gs4a3h" +
            "ruGv4bDhseGy4bPhtOG14bbhAAC34bjhueG64bvhvOG94b7hv+HA4cHhwuHD4cThxeHG4cfhyOHJ4crhy+HM4c3hzuHP4dDh0eHS4dPh1OHV4dbh1+HY4dnh" +
            "2uHb4dzh3eHe4d/h4OHh4eLh4+Hk4eXh5uHn4ejh6eHq4evh7OHt4e7h7+Hw4fHh8uHz4fTh9eH24ffh+OH54frh++H84f3h/uH/4QDiAeIC4gPiBOIF4gbi" +
            "B+II4gniCuIL4gziDeIO4g/iEOIR4hLiE+IU4hXiFuIX4hjiGeIa4hviHOId4h7iH+Ig4iHiIuIj4iTiJeIm4ifiKOIp4iriK+Is4i3iLuIv4jDiMeIy4jPi" +
            "NOI14jbiN+I44jniOuI74jziPeI+4j/iQOJB4kLiQ+JE4kXiRuJH4kjiSeJK4kviTOJN4k7iT+JQ4lHiUuJT4lTiVeJW4lfiWOJZ4lriW+Jc4l3iXuJf4mDi" +
            "YeJi4mPiZOJl4mbiZ+Jo4mniauJr4mzibeJu4m/icOJx4nLiAABz4nTideJ24nfieOJ54nrie+J84n3ifuJ/4oDigeKC4oPihOKF4obih+KI4oniiuKL4ozi" +
            "jeKO4o/ikOKR4pLik+KU4pXiluKX4pjimeKa4pvinOKd4p7in+Kg4qHiouKj4qTipeKm4qfiqOKp4qriq+Ks4q3iruKv4rDiseKy4rPitOK14rbit+K44rni" +
            "uuK74rziveK+4r/iwOLB4sLiw+LE4sXixuLH4sjiyeLK4svizOLN4s7iz+LQ4tHi0uLT4tTi1eLW4tfi2OLZ4tri2+Lc4t3i3uLf4uDi4eLi4uPi5OLl4ubi" +
            "5+Lo4uni6uLr4uzi7eLu4u/i8OLx4vLi8+L04vXi9uL34vji+eL64vvi/OL94v7i/+IA4wHjAuMD4wTjBeMG4wfjCOMJ4wrjC+MM4w3jDuMP4xDjEeMS4xPj" +
            "FOMV4xbjF+MY4xnjGuMb4xzjHeMe4x/jIOMh4yLjI+Mk4yXjJuMn4yjjKeMq4yvjLOMt4y7jAAAv4zDjMeMy4zPjNOM14zbjN+M44znjOuM74zzjPeM+4z/j" +
            "QONB40LjQ+NE40XjRuNH40jjSeNK40vjTONN407jT+NQ41HjUuNT41TjVeNW41fjWONZ41rjW+Nc413jXuNf42DjYeNi42PjZONl42bjZ+No42njauNr42zj" +
            "beNu42/jcONx43Ljc+N043XjduN343jjeeN643vjfON9437jf+OA44HjguOD44TjheOG44fjiOOJ44rji+OM443jjuOP45DjkeOS45PjlOOV45bjl+OY45nj" +
            "muOb45zjneOe45/joOOh46Ljo+Ok46XjpuOn46jjqeOq46vjrOOt467jr+Ow47HjsuOz47TjteO247fjuOO547rju+O8473jvuO/48DjwePC48PjxOPF48bj" +
            "x+PI48njyuPL48zjzePO48/j0OPR49Lj0+PU49Xj1uPX49jj2ePa49vj3OPd497j3+Pg4+Hj4uPj4+Tj5ePm4+fj6OPp4+rjAADr4+zj7ePu4+/j8OPx4/Lj" +
            "8+P04/Xj9uP34/jj+eP64/vj/OP94/7j/+MA5AHkAuQD5ATkBeQG5AfkCOQJ5ArkC+QM5A3kDuQP5BDkEeQS5BPkFOQV5BbkF+QY5BnkGuQb5BzkHeQe5B/k" +
            "IOQh5CLkI+Qk5CXkJuQn5CjkKeQq5CvkLOQt5C7kL+Qw5DHkMuQz5DTkNeQ25DfkOOQ55DrkO+Q85D3kPuQ/5EDkQeRC5EPkRORF5EbkR+RI5EnkSuRL5Ezk" +
            "TeRO5E/kUORR5FLkU+RU5FXkVuRX5FjkWeRa5FvkXORd5F7kX+Rg5GHkYuRj5GTkZeRm5GfkaORp5Grka+Rs5G3kbuRv5HDkceRy5HPkdOR15Hbkd+R45Hnk" +
            "euR75HzkfeR+5H/kgOSB5ILkg+SE5IXkhuSH5IjkieSK5IvkjOSN5I7kj+SQ5JHkkuST5JTkleSW5JfkmOSZ5Jrkm+Sc5J3knuSf5KDkoeSi5KPkpOSl5Kbk" +
            "AACn5KjkqeSq5KvkrOSt5K7kr+Sw5LHksuSz5LTkteS25LfkuOS55Lrku+S85L3kvuS/5MDkweTC5MPkxOTF5Mbkx+TI5MnkyuTL5MzkzeTO5M/k0OTR5NLk" +
            "0+TU5NXk1uTX5Njk2eTa5Nvk3OTd5N7k3+Tg5OHk4uTj5OTk5eTm5Ofk6OTp5Ork6+Ts5O3k7uTv5PDk8eTy5PPk9OT15Pbk9+T45Pnk+uT75Pzk/eT+5P/k" +
            "AOUB5QLlA+UE5QXlBuUH5QjlCeUK5QvlDOUN5Q7lD+UQ5RHlEuUT5RTlFeUW5RflGOUZ5RrlG+Uc5R3lHuUf5SDlIeUi5SPlJOUl5SblJ+Uo5SnlKuUr5Szl" +
            "LeUu5S/lMOUx5TLlM+U05TXlNuU35TjlOeU65TvlPOU95T7lP+VA5UHlQuVD5UTlReVG5UflSOVJ5UrlS+VM5U3lTuVP5VDlUeVS5VPlVOVV5VblV+VY5Vnl" +
            "WuVb5VzlXeVe5V/lYOVh5WLlAABj5WTlZeVm5WflaOVp5Wrla+Vs5W3lbuVv5XDlceVy5XPldOV15Xbld+V45XnleuV75XzlfeV+5X/lgOWB5YLlg+WE5YXl" +
            "huWH5YjlieWK5YvljOWN5Y7lj+WQ5ZHlkuWT5ZTlleWW5ZflmOWZ5Zrlm+Wc5Z3lnuWf5aDloeWi5aPlpOWl5ablp+Wo5anlquWr5azlreWu5a/lsOWx5bLl" +
            "s+W05bXltuW35bjlueW65bvlvOW95b7lv+XA5cHlwuXD5cTlxeXG5cflyOXJ5crly+XM5c3lzuXP5dDl0eXS5dPl1OXV5dbl1+XY5dnl2uXb5dzl3eXe5d/l" +
            "4OXh5eLl4+Xk5eXl5uXn5ejl6eXq5evl7OXt5e7l7+Xw5fHl8uXz5fTl9eX25ffl+OX55frl++X85f3l/uX/5QDmAeYC5gPmBOYF5gbmB+YI5gnmCuYL5gzm" +
            "DeYO5g/mEOYR5hLmE+YU5hXmFuYX5hjmGeYa5hvmHOYd5h7mAAAf5iDmIeYi5iPmJOYl5ibmJ+Yo5inmKuYr5izmLeYu5i/mMOYx5jLmM+Y05jXmNuY35jjm" +
            "OeY65jvmPOY95j7mP+ZA5kHmQuZD5kTmReZG5kfmSOZJ5krmS+ZM5k3mTuZP5lDmUeZS5lPmVOZV5lbmV+ZY5lnmWuZb5lzmXeZe5l/mYOZh5mLmY+Zk5mXm" +
            "ZuZn5mjmaeZq5mvmbOZt5m7mb+Zw5nHmcuZz5nTmdeZ25nfmeOZ55nrme+Z85n3mfuZ/5oDmgeaC5oPmhOaF5obmh+aI5onmiuaL5ozmjeaO5o/mkOaR5pLm" +
            "k+aU5pXmluaX5pjmmeaa5pvmnOad5p7mn+ag5qHmouaj5qTmpeam5qfmqOap5qrmq+as5q3mruav5rDmseay5rPmtOa15rbmt+a45rnmuua75rzmvea+5r/m" +
            "wObB5sLmw+bE5sXmxubH5sjmyebK5svmzObN5s7mz+bQ5tHm0ubT5tTm1ebW5tfm2ObZ5trmAADb5tzm3ebe5t/m4Obh5uLm4+bk5uXm5ubn5ujm6ebq5uvm" +
            "7Obt5u7m7+bw5vHm8ubz5vTm9eb25vfm+Ob55vrm++b85v3m/ub/5gDnAecC5wPnBOcF5wbnB+cI5wnnCucL5wznDecO5w/nEOcR5xLnE+cU5xXnFucX5xjn" +
            "Geca5xvnHOcd5x7nH+cg5yHnIucj5yTnJecm5yfnKOcp5yrnK+cs5y3nLucv5zDnMecy5zPnNOc15zbnN+c45znnOuc75zznPec+5z/nQOdB50LnQ+dE50Xn" +
            "RudH50jnSedK50vnTOdN507nT+dQ51HnUudT51TnVedW51fncCFxIXIhcyF0IXUhdiF3IXgheSFgIWEhYiFjIWQhZSFmIWchaCFpIeL/5P8H/wL/MTIWISEh" +
            "NSKKfhyJSJOIktyEyU+7cDFmyGj5kvtmRV8oTuFO/E4ATwNPOU9WT5JPik+aT5RPzU9AUCJQ/08eUEZQcFBCUJRQ9FDYUEpRAABkUZ1RvlHsURVSnFKmUsBS" +
            "21IAUwdTJFNyU5NTslPdUw76nFSKVKlU/1SGVVlXZVesV8hXx1cP+hD6nliyWAtZU1lbWV1ZY1mkWbpZVlvAWy912FvsWx5cply6XPVcJ11TXRH6Ql1tXbhd" +
            "uV3QXSFfNF9nX7df3l9dYIVgimDeYNVgIGHyYBFhN2EwYZhhE2KmYvVjYGSdZM5kTmUAZhVmO2YJZi5mHmYkZmVmV2ZZZhL6c2aZZqBmsma/ZvpmDmcp+WZn" +
            "u2dSaMBnAWhEaM9oE/poaRT6mGniaTBqa2pGanNqfmriauRq1ms/bFxshmxvbNpsBG2HbW9tlm2sbc9t+G3ybfxtOW5cbiduPG6/bohvtW/1bwVwB3AocIVw" +
            "q3APcQRxXHFGcUdxFfrBcf5xsXK+ciRzFvp3c71zyXPWc+Nz0nMHdPVzJnQqdCl0LnRidIl0n3QBdW91gnacdp52m3amdhf6RnevUiF4TnhkeHp4MHkY+hn6" +
            "AAAa+pR5G/qbedF653oc+ut6nnsd+kh9XH23faB91n1Sfkd/oX8e+gGDYoN/g8eD9oNIhLSEU4VZhWuFH/qwhSD6IfoHiPWIEoo3inmKp4q+it+KIvr2ilOL" +
            "f4vwjPSMEo12jSP6z44k+iX6Z5DekCb6FZEnkdqR15Heke2R7pHkkeWRBpIQkgqSOpJAkjySTpJZklGSOZJnkqeSd5J4kueS15LZktCSJ/rVkuCS05IlkyGT" +
            "+5Io+h6T/5IdkwKTcJNXk6STxpPek/iTMZRFlEiUkpXc+Sn6nZavljOXO5dDl02XT5dRl1WXV5hlmCr6K/onmSz6nplOmtma3Jp1m3Kbj5uxm7ubAJxwnWud" +
            "LfoZntGe+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPswAAD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw" +
            "+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw+zD7MPsw";

        private static ushort[] SingleByte => s_SingleByte ??= Decode(k_SingleByteBase64);
        private static ushort[] DoubleByte => s_DoubleByte ??= Decode(k_DoubleByteBase64);

        private static ushort[] Decode(string base64)
        {
            byte[] bytes = Convert.FromBase64String(base64);
            ushort[] table = new ushort[bytes.Length / 2];
            Buffer.BlockCopy(bytes, 0, table, 0, bytes.Length);
            return table;
        }

        /// <summary>
        /// Decodes <paramref name="count"/> CP932 bytes starting at <paramref name="index"/> into a string.
        /// </summary>
        public static string GetString(byte[] bytes, int index, int count)
        {
            if (bytes == null)
            {
                throw new ArgumentNullException(nameof(bytes));
            }
            if (index < 0 || count < 0 || index + count > bytes.Length)
            {
                throw new ArgumentOutOfRangeException(nameof(count));
            }

            ushort[] single = SingleByte;
            ushort[] dbcs = DoubleByte;
            StringBuilder builder = new StringBuilder(count);
            int end = index + count;
            int i = index;
            while (i < end)
            {
                ushort mapped = single[bytes[i]];
                if (mapped != k_DoubleByteLead)
                {
                    builder.Append((char)mapped); // direct single-byte mapping (0xFFFD for undefined bytes)
                    ++i;
                    continue;
                }

                int leadIndex = LeadIndex(bytes[i]);
                if (leadIndex >= 0 && i + 1 < end)
                {
                    byte trail = bytes[i + 1];
                    if (trail >= k_TrailStart && trail <= k_TrailEnd && trail != 0x7F)
                    {
                        ushort code = dbcs[leadIndex * k_TrailCount + (trail - k_TrailStart)];
                        builder.Append(code != 0 ? (char)code : k_Replacement);
                        i += 2;
                        continue;
                    }
                }

                builder.Append(k_Replacement);
                ++i;
            }

            return builder.ToString();
        }

        // Maps a lead byte to its row index in the double-byte table, or -1 if it is not a valid lead.
        private static int LeadIndex(byte lead)
        {
            if (lead >= 0x81 && lead <= 0x9F)
            {
                return lead - 0x81;
            }
            if (lead >= 0xE0 && lead <= 0xFC)
            {
                return (0x9F - 0x81 + 1) + (lead - 0xE0);
            }
            return -1;
        }
    }
}